######################## default configuration ####################
baseURL = "https://harstad.co/"
title = "Ravings of a Mad Engineer"
theme = "mytheme"
disqusShortname = "madengineer"
googleAnalytics = "G-DSLFFY0YVC"

[params]
  logo = 'icon-logo.svg'

[taxonomies]
  category = 'categories'
  series = 'series'
  target = 'targets'
  image-series = 'image-series'
  image-session = 'image-sessions'

############################# Modules ##############################
[module]
  [module.hugoVersion]
    extended = true
    # min = "0.89.4"
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"
