baseurl = "https://harstad.co/"
paginate = 10
theme = "hugo-clarity"
disqusShortname = ""

DefaultContentLanguage = "en"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
  home = ["HTML", "RSS","JSON"]
