######################## default configuration ####################
baseURL = "https://harstad.dev/"
title = "Ravings of a Mad Engineer"
theme = "mytheme"
disqusShortname = "madengineer"
googleAnalytics = "G-DSLFFY0YVC"

[params]
  logo = 'icon-logo.svg'
  paginate = 10

[outputFormats]
  [outputFormats.SearchIndex]
    baseName = 'search'
    mediaType = 'application/json'

[outputs]
  home = ['HTML', 'RSS', 'SearchIndex']

[taxonomies]
  category = 'categories'
  series = 'series'
  target = 'targets'
  image-series = 'image-series'
  image-session = 'image-sessions'

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'series'
  weight = 100
[[related.indices]]
  name = 'categories'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80
[[related.indices]]
  name = 'date'
  weight = 10

############################# Modules ##############################
[module]
  [module.hugoVersion]
    extended = true
    # min = "0.89.4"
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"
  [[module.mounts]]
    source = "assets"
    target = "assets"
